class eos_config::mlag (
  $domain_id,
  $members,
  $local_interface,
  $local_address,
  $peer_address,
  $peer_link,
)  {

  eos_vlan { '4094':
    vlan_name => 'MLAG_Control_Plane',
    #trunk_groups => ['mlag1', 'mlag2'],
    #trunk_groups => ['mlagpeer'],
    before    => Eos_mlag['settings'],
  }

  eos_interface { $peer_link:
    description => 'autogenerated by eos_config::mlag',
    require     => Eos_vlan['4094'],
  }

  eos_interface { $local_interface:
    description => 'autogenerated by eos_config::mlag',
    require     => Eos_vlan['4094'],
  }

  eos_ipinterface { $local_interface:
    ensure  => present,
    #address => "172.16.10.1/24",
    address => $local_address,
    require => Eos_interface[$local_interface],
  }

  eos_config::mlag::member { $members: }

  eos_portchannel { $peer_link:
    ensure    => present,
    lacp_mode => active,
    members   => $members,
    require   => Eos_interface[$peer_link],
  }

  eos_switchport { $peer_link:
    ensure  => present,
    mode    => trunk,
    require => Eos_interface[$peer_link],
    # ToDo: Need trunk_group property
  }

  eos_mlag { 'settings':
    domain_id       => $domain_id,
    local_interface => $local_interface,
    peer_address    => $peer_address,
    peer_link       => $peer_link,
    enable          => true,
  }
}
