#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To initialize this hook in your workspace, run the following from the top
#   ln -s hooks/pre-commit .git/hooks/pre-commit

git stash -q --keep-index
bundle exec rake lint
RESULT=$?
git stash pop -q
[ $RESULT -ne 0 ] && exit 1
exit 0
