define eos_config::switchport::access {
  eos_interface { $name:
    enable      => true,
    description => 'autogenerated by eos_config::switchport::access',
  }

  eos_switchport { $name:
    mode => access,
  }
}
