define eos_config::switchport::trunk {
  eos_interface { $name:
    enable      => true,
    description => 'autogenerated by eos_config::switchport::trunk',
  }

  eos_switchport { $name:
    mode => trunk,
  }
}
